"use strict";
exports.__esModule = true;
var defectList = [
    {
        defectId: 'D-001',
        title: 'Login page not rendering properly',
        description: 'The login page layout is distorted on smaller screens.',
        owners: ['John Doe', 'Jane Smith'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-01'
    },
    {
        defectId: 'D-002',
        title: 'Missing validation on email field',
        description: 'The email field allows invalid input without any validation.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-02'
    },
    {
        defectId: 'D-003',
        title: 'Incorrect calculations in revenue report',
        description: 'The revenue report is displaying incorrect totals for some months.',
        owners: ['Jane Smith', 'Emily Davis'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-03'
    },
    {
        defectId: 'D-004',
        title: 'Mobile app crashes on iOS',
        description: 'The mobile app crashes immediately after launching on iOS devices.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'High',
        environment: 'Mobile',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-04'
    },
    {
        defectId: 'D-005',
        title: 'Broken links on the homepage',
        description: 'Several links on the homepage are not working and lead to error pages.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-05'
    },
    {
        defectId: 'D-006',
        title: 'Incorrect currency symbol on pricing page',
        description: 'The pricing page shows the wrong currency symbol for the selected country.',
        owners: ['John Doe', 'Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-06'
    },
    {
        defectId: 'D-007',
        title: 'Slow performance when loading large datasets',
        description: 'The application becomes unresponsive when loading large datasets.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-07'
    },
    {
        defectId: 'D-008',
        title: 'Incorrect sorting of table columns',
        description: 'The table columns are not sorting correctly when clicked on the header.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-08'
    },
    {
        defectId: 'D-009',
        title: 'Missing field labels on form',
        description: 'Some fields on the form are missing their corresponding labels.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-09'
    },
    {
        defectId: 'D-010',
        title: 'Mobile app crashes on Android',
        description: 'The mobile app crashes immediately after launching on Android devices.',
        owners: ['John Doe', 'Emily Davis'],
        status: 'Open',
        priority: 'High',
        environment: 'Mobile',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-10'
    },
    {
        defectId: 'D-011',
        title: 'Incorrect permissions for user roles',
        description: 'Some user roles are granted incorrect permissions and can access restricted areas.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-11'
    },
    {
        defectId: 'D-012',
        title: 'Image upload not working',
        description: 'The image upload feature is not functioning properly and throws an error.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-12'
    },
    {
        defectId: 'D-013',
        title: 'Slow response time on search',
        description: 'The search functionality takes too long to respond when searching for keywords.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-13'
    },
    {
        defectId: 'D-014',
        title: 'Incorrect display of dates in calendar',
        description: 'The dates in the calendar are not displayed correctly for certain time zones.',
        owners: ['John Doe', 'Jane Smith'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-14'
    },
    {
        defectId: 'D-015',
        title: 'Missing error message on login failure',
        description: 'When a user enters incorrect login credentials, no error message is displayed.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-15'
    },
    {
        defectId: 'D-016',
        title: 'High memory usage on data export',
        description: 'Exporting large datasets consumes excessive memory and causes performance issues.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-16'
    },
    {
        defectId: 'D-017',
        title: 'Incorrect display of product images',
        description: 'The product images are not showing up correctly and appear distorted.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-17'
    },
    {
        defectId: 'D-018',
        title: 'Missing validation on password field',
        description: 'The password field does not have any validation, allowing weak passwords.',
        owners: ['John Doe', 'Emily Davis'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-18'
    },
    {
        defectId: 'D-019',
        title: 'Mobile app freezes randomly',
        description: 'The mobile app becomes unresponsive and freezes randomly during usage.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'High',
        environment: 'Mobile',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-19'
    },
    {
        defectId: 'D-020',
        title: 'Incorrect calculations in expense report',
        description: 'The expense report is displaying incorrect totals for certain categories.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-20'
    },
    {
        defectId: 'D-021',
        title: 'Broken pagination on product listing',
        description: 'The pagination on the product listing page is not working and shows incorrect results.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-21'
    },
    {
        defectId: 'D-022',
        title: 'Slow loading of customer profiles',
        description: 'Loading customer profiles takes a significant amount of time, impacting user experience.',
        owners: ['John Doe', 'Jane Smith'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-22'
    },
    {
        defectId: 'D-023',
        title: 'Incorrect display of order total',
        description: 'The order total is not calculated correctly and shows an incorrect amount.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-23'
    },
    {
        defectId: 'D-024',
        title: 'Email notifications not being sent',
        description: 'The email notifications for certain events are not being sent to users.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-24'
    },
    {
        defectId: 'D-025',
        title: 'Broken search functionality',
        description: 'The search feature does not return accurate results and fails to find matching items.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-25'
    },
    {
        defectId: 'D-026',
        title: 'Mobile app crashes when accessing camera',
        description: 'The mobile app crashes when attempting to access the camera feature.',
        owners: ['John Doe', 'Emily Davis'],
        status: 'Open',
        priority: 'High',
        environment: 'Mobile',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-26'
    },
    {
        defectId: 'D-027',
        title: 'Incorrect display of product availability',
        description: 'The product availability status is not being displayed accurately on the product page.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-27'
    },
    {
        defectId: 'D-028',
        title: 'Missing confirmation dialog on delete action',
        description: 'When performing a delete action, there is no confirmation dialog to prevent accidental deletions.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-28'
    },
    {
        defectId: 'D-029',
        title: 'Slow loading of product images',
        description: 'Loading product images takes a long time, causing delays in the product page loading.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-29'
    },
    {
        defectId: 'D-030',
        title: 'Incorrect display of customer names',
        description: 'The customer names are not being displayed correctly in the customer list.',
        owners: ['John Doe', 'Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-05-30'
    },
    {
        defectId: 'D-031',
        title: 'Missing field validation on checkout form',
        description: 'The checkout form does not have proper validation, allowing incomplete submissions.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-05-31'
    },
    {
        defectId: 'D-032',
        title: 'Mobile app crashes on certain devices',
        description: 'The mobile app crashes consistently on specific devices running a certain OS version.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Low',
        environment: 'Mobile',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-01'
    },
    {
        defectId: 'D-033',
        title: 'Incorrect display of order history',
        description: 'The order history for some customers is not displayed correctly, showing duplicate entries.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-02'
    },
    {
        defectId: 'D-034',
        title: 'Missing error handling on API requests',
        description: 'The application does not handle API request errors properly, resulting in unexpected behavior.',
        owners: ['John Doe', 'Emily Davis'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-03'
    },
    {
        defectId: 'D-035',
        title: 'Broken formatting on order confirmation email',
        description: 'The order confirmation email is not properly formatted and displays incorrect information.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-04'
    },
    {
        defectId: 'D-036',
        title: 'Missing validation on discount code field',
        description: 'The discount code field does not have any validation, allowing invalid codes.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-05'
    },
    {
        defectId: 'D-037',
        title: 'Incorrect display of shipping rates',
        description: 'The shipping rates are not displayed correctly during the checkout process.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-06'
    },
    {
        defectId: 'D-038',
        title: 'Slow loading of order details',
        description: 'Loading order details takes too long, causing delays when viewing order information.',
        owners: ['John Doe', 'Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-07'
    },
    {
        defectId: 'D-039',
        title: 'Incorrect display of discount amount',
        description: 'The discount amount is not calculated correctly and displays an incorrect value.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-08'
    },
    {
        defectId: 'D-040',
        title: 'Mobile app crashes on login',
        description: 'The mobile app crashes when attempting to log in, preventing users from accessing the app.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'High',
        environment: 'Mobile',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-09'
    },
    {
        defectId: 'D-041',
        title: 'Missing field validation on registration form',
        description: 'The registration form does not have proper validation, allowing incomplete submissions.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-10'
    },
    {
        defectId: 'D-042',
        title: 'Broken password reset functionality',
        description: 'The password reset feature is not functioning properly and does not send reset emails.',
        owners: ['John Doe', 'Emily Davis'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-11'
    },
    {
        defectId: 'D-043',
        title: 'Slow loading of product categories',
        description: 'Loading product categories takes too long, affecting the navigation performance.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'High',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-12'
    },
    {
        defectId: 'D-044',
        title: 'Missing error handling on form submissions',
        description: 'Form submissions do not display error messages when there are validation or server-side issues.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-13'
    },
    {
        defectId: 'D-045',
        title: 'Incorrect display of customer addresses',
        description: 'The customer addresses are not being displayed correctly in the customer profile.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-14'
    },
    {
        defectId: 'D-046',
        title: 'Broken filtering on product search',
        description: 'The filtering functionality on the product search page is not working and does not filter results.',
        owners: ['John Doe', 'Jane Smith'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-15'
    },
    {
        defectId: 'D-047',
        title: 'Slow response time on product details',
        description: 'Loading the product details page takes too long, impacting user experience.',
        owners: ['Emily Davis'],
        status: 'Open',
        priority: 'Low',
        environment: 'Web',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-16'
    },
    {
        defectId: 'D-048',
        title: 'Missing validation on credit card information',
        description: 'The credit card information fields do not have proper validation, allowing invalid entries.',
        owners: ['John Doe'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-17'
    },
    {
        defectId: 'D-049',
        title: 'Mobile app crashes when opening notifications',
        description: 'The mobile app crashes when attempting to open the notifications section.',
        owners: ['Jane Smith'],
        status: 'Open',
        priority: 'High',
        environment: 'Mobile',
        createdBy: 'Alice Johnson',
        createdDate: '2023-06-18'
    },
    {
        defectId: 'D-050',
        title: 'Incorrect display of product ratings',
        description: 'The product ratings are not being displayed correctly on the product page.',
        owners: ['John Doe', 'Emily Davis'],
        status: 'Open',
        priority: 'Medium',
        environment: 'Web',
        createdBy: 'Bob Thompson',
        createdDate: '2023-06-19'
    }
];
exports["default"] = defectList;
